export const PRODUCT_CATEGORIES = [
  {
    id: "frutas_verduras",
    name: "Frutas y verduras",
    image: require("../assets/categories/1.png"),
    subcategories: [
      "Manzana",
      "Platano",
      "Naranja",
      "Mandarina",
      "Limon",
      "Pera",
      "Uva",
      "Fresa",
      "Kiwi",
      "Melon",
      "Sandia",
      "Tomate",
      "Lechuga",
      "Zanahoria",
      "Patata",
      "Cebolla",
    ],
  },
  {
    id: "carnes_pescados",
    name: "Carne y pescado",
    image: require("../assets/categories/2.png"),
    subcategories: [
      "Pollo",
      "Ternera",
      "Cerdo",
      "Pavo",
      "Conejo",
      "Cordero",
      "Hamburguesa",
      "Salchicha",
      "Bacon",
      "Jamon",
      "Merluza",
      "Salmon",
      "Atun",
      "Sardina",
      "Bacalao",
      "Gambas",
    ],
  },
  {
    id: "panaderia_bolleria",
    name: "Panadería",
    image: require("../assets/categories/3.png"),
    subcategories: [
      "Pan",
      "Baguette",
      "Molde",
      "Integral",
      "Centeno",
      "Chapata",
      "Picos",
      "Tostadas",
      "Croissant",
      "Magdalena",
      "Donut",
      "Napolitana",
      "Ensaimada",
      "Bizcocho",
      "Palmeras",
      "Bolleria",
    ],
  },
  {
    id: "lacteos_huevos",
    name: "Lácteos y huevos",
    image: require("../assets/categories/4.png"),
    subcategories: [
      "Leche",
      "Yogur",
      "Queso",
      "Huevos",
      "Mantequilla",
      "Nata",
      "Cuajada",
      "Flan",
      "Kefir",
      "Mozzarella",
      "Burgos",
      "Cheddar",
      "Gouda",
      "Requeson",
      "Batido",
      "Natillas",
    ],
  },
  {
    id: "refrigerados",
    name: "Refrigerados",
    image: require("../assets/categories/5.png"),
    subcategories: [
      "Pavo",
      "Jamon",
      "Chorizo",
      "Salami",
      "Mortadela",
      "Salchichas",
      "Bacon",
      "Pate",
      "Gazpacho",
      "Tortilla",
      "Ensaladilla",
      "Hummus",
      "Pizza",
      "Pasta",
      "Queso",
      "Sushi",
    ],
  },
  {
    id: "congelados",
    name: "Congelados",
    image: require("../assets/categories/6.png"),
    subcategories: [
      "Pizza",
      "Helado",
      "Croquetas",
      "Patatas",
      "Verduras",
      "Guisantes",
      "Espinacas",
      "Pescado",
      "Merluza",
      "Gambas",
      "Calamares",
      "Pollo",
      "Lasana",
      "Empanadillas",
      "Nuggets",
      "Wok",
    ],
  },
  {
    id: "despensa",
    name: "Despensa",
    image: require("../assets/categories/7.png"),
    subcategories: [
      "Arroz",
      "Pasta",
      "Fideos",
      "Lentejas",
      "Garbanzos",
      "Alubias",
      "Aceite",
      "Vinagre",
      "Sal",
      "Azucar",
      "Harina",
      "Conservas",
      "Atun",
      "Tomate",
      "Cereales",
      "Cafe",
    ],
  },
  {
    id: "bebidas",
    name: "Bebidas",
    image: require("../assets/categories/8.png"),
    subcategories: [
      "Agua",
      "Refresco",
      "Zumo",
      "Cafe",
      "Te",
      "Cacao",
      "Batido",
      "Horchata",
      "Tonica",
      "Gaseosa",
      "Isotonica",
      "Energia",
      "Limonada",
      "Infusion",
      "Soda",
      "Kombucha",
    ],
  },
  {
    id: "dulces_aperitivos",
    name: "Dulces y aperitivos",
    image: require("../assets/categories/9.png"),
    subcategories: [
      "Chocolate",
      "Galletas",
      "Patatas",
      "Palomitas",
      "Cacahuetes",
      "Pipas",
      "Pistachos",
      "Almendras",
      "Avellanas",
      "Caramelos",
      "Chicles",
      "Gominolas",
      "Barritas",
      "Turron",
      "Bombones",
      "Nachos",
    ],
  },
  {
    id: "higiene_personal",
    name: "Higiene personal",
    image: require("../assets/categories/10.png"),
    subcategories: [
      "Champu",
      "Gel",
      "Jabon",
      "Dentifrico",
      "Cepillo",
      "Enjuague",
      "Desodorante",
      "Colonia",
      "Maquinillas",
      "Cuchillas",
      "Compresas",
      "Tampones",
      "Panuelos",
      "Bastoncillos",
      "Crema",
      "Toallitas",
    ],
  },
  {
    id: "limpieza_hogar",
    name: "Limpieza del hogar",
    image: require("../assets/categories/11.png"),
    subcategories: [
      "Detergente",
      "Suavizante",
      "Lejia",
      "Amoniaco",
      "Fregasuelos",
      "Lavavajillas",
      "Estropajos",
      "Bayetas",
      "Guantes",
      "Ambientador",
      "Bolsas",
      "Papel",
      "Desinfectante",
      "Cristales",
      "Quitagrasas",
      "Insecticida",
    ],
  },
  {
    id: "bebe",
    name: "Bebé",
    image: require("../assets/categories/12.png"),
    subcategories: [
      "Panales",
      "Toallitas",
      "Potitos",
      "Papillas",
      "Biberon",
      "Chupete",
      "Leche",
      "Cereales",
      "Galletas",
      "Crema",
      "Champu",
      "Gel",
      "Colonia",
      "Babero",
      "Juguete",
      "Mordedor",
    ],
  },
  {
    id: "mascotas",
    name: "Mascotas",
    image: require("../assets/categories/13.png"),
    subcategories: [
      "Pienso",
      "Latas",
      "Snacks",
      "Arena",
      "Correa",
      "Collar",
      "Juguetes",
      "Champu",
      "Comedero",
      "Bebedero",
      "Bolsas",
      "Higiene",
      "Perro",
      "Gato",
      "Pajaros",
      "Roedores",
    ],
  },
  {
    id: "hogar_bazar",
    name: "Hogar y bazar",
    image: require("../assets/categories/14.png"),
    subcategories: [
      "Pilas",
      "Velas",
      "Servilletas",
      "Vasos",
      "Platos",
      "Cubiertos",
      "Aluminio",
      "Film",
      "Bolsas",
      "Perchas",
      "Menaje",
      "Tupper",
      "Escobas",
      "Fregonas",
      "Bombillas",
      "Cuerda",
    ],
  },
  {
    id: "salud_parafarmacia",
    name: "Salud y parafarmacia",
    image: require("../assets/categories/15.png"),
    subcategories: [
      "Tiritas",
      "Alcohol",
      "Gasas",
      "Vendas",
      "Suero",
      "Vitaminas",
      "Termometro",
      "Mascarillas",
      "Guantes",
      "Crema",
      "Solar",
      "Colirio",
      "Gel",
      "Pastillero",
      "Repelente",
      "Algodon",
    ],
  },
  {
    id: "dietetica_ecologico",
    name: "Dietética y ecológico",
    image: require("../assets/categories/16.png"),
    subcategories: [
      "Tofu",
      "Seitan",
      "Quinoa",
      "Avena",
      "Soja",
      "Integral",
      "Bio",
      "Eco",
      "Sin_gluten",
      "Sin_lactosa",
      "Vegano",
      "Proteina",
      "Chia",
      "Granola",
      "Muesli",
      "Almendra",
    ],
  },
];
